services:
  # Cart Database
  mongo-cart:
    image: mongo:4.4
    container_name: mongo-cart
    restart: always
      #    ports:
      # - "27018:27017" # Host 27023 -> Container 27017
    networks:
      - app-network

  # Cart Service
  goapp-cart:
    build: ./cart-service
    container_name: goapp-cart
      #  ports:
      #- "8080:8085"
    depends_on:
      - mongo-cart
    environment:
      # The app connects to the service name 'mongo-cart' on internal port 27017
      - MONGO_URI=mongodb://mongo-cart:27017/
    networks:
      - app-network


# Notification Service
  goapp-notification:
    build: ./notification-service
    container_name: goapp-notification
      #ports:
      #- "8081:8084" # Mapping Host 8081 to Container 8081
    env_file:
      - .env # Automatically loads your TWILIO_API_KEY, etc.
    networks:
      - app-network


# --- USER SERVICE STACK ---

  mongo-user:
    image: mongo:4.4
    container_name: mongo-user
      #ports:
      #- "27019:27017"
    networks:
      - app-network

  goapp-user:
    build: ./user-service
    container_name: goapp-user
      #ports:
      #- "8082:8080"    # Mapping Host 8081 to Container 8081
    depends_on:
      - mongo-user
    environment:
      - MONGO_URI=mongodb://mongo-user:27017/
    networks:
      - app-network



# Order Database
  mongo-order:
    image: mongo:4.4
    container_name: mongo-order
    restart: always
      #ports:
      #- "27020:27017" # Host 27020 -> Container 27017
    networks:
      - app-network

  # Order Service
  goapp-order:
    build: ./order-service
    container_name: goapp-order
      #ports:
      #- "8083:8083" # Mapping Host 8083 to Container 8083
    depends_on:
      - mongo-order
    environment:
      - MONGO_URI=mongodb://mongo-order:27017/
    networks:
      - app-network




# Payment Database
  mongo-payment:
    image: mongo:4.4
    container_name: mongo-payment
    restart: always
      # ports:
      #- "27021:27017"
    networks:
      - app-network

  # Payment Service
  goapp-payment:
    build: ./payment-service
    container_name: goapp-payment
      #ports:
      #- "8084:8082" # Maps host 8083 to your payment service's port 8083
    depends_on:
      - mongo-payment
    env_file:
      - .env # Crucial for pulling in the STRIPE_API key
    environment:
      - MONGO_URI=mongodb://mongo-payment:27017/
    networks:
      - app-network







# Product Database
  mongo-product:
    image: mongo:4.4
    container_name: mongo-product
    restart: always
      #ports:
      #- "27022:27017" # Host 27022 -> Container 27017
    networks:
      - app-network

  # Product Service
  goapp-product:
    build: ./product-service
    container_name: goapp-product
      #ports:
      #- "8085:8081" # Map host 8085 to internal 8085
    depends_on:
      - mongo-product
    environment:
      - MONGO_URI=mongodb://mongo-product:27017/productdb
    networks:
      - app-network
  


  api-gateway:
    image: nginx:alpine
    container_name: api-gateway
    ports:
      - "8000:80"  # This is the front door for all your services
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro  # This swaps the files
    depends_on:
      - goapp-user
      - goapp-product
      - goapp-cart
      - goapp-notification
      - goapp-order
      - goapp-payment
    networks:
      - app-network     


networks:
  app-network:
    driver: bridge
