# The "Boss" level - global settings
events {
    worker_connections 1024;
}

http {
    # 1. THE LIST: Define all your microservices here
    
    upstream product-service {
        server goapp-product:8081;
    }

    upstream payment-service {
	
	server goapp-payment:8082; 

    }

    upstream order-service {

	server goapp-order:8083;

    }

    upstream users-service {

  	server goapp-user:8080;

    }

    upstream notification-service {

	server goapp-notification:8084;

    }

    upstream cart-service {
	server goapp-cart:8085;

    }

    # 2. THE ROUTER: Tell Nginx how to handle requests
    server {
        listen 80;

        # If the URL is localhost:8000/users/, go to the user-service
        location /users/ {
            proxy_pass http://users-service/;
        }

        # If the URL is localhost:8000/products/, go to the product-service
        location /products/ {
            proxy_pass http://product-service/;
        }


	location /payment/ {
	    proxy_pass http://payment-service/;
	}

	location /order/ {
	    proxy_pass http://order-service/;
	}

	location /notification/ {
	    proxy_pass http://notification-service/;
	}

	location /cart/ {
	    proxy_pass http://cart-service/;
	}
    }
}
