services:
  mongo:
    container_name: mongo-product
    image: mongo:4.4
    restart: always
    ports:
      - "27019:27017" # Host 27019 -> Container 27017
  

  goapp:
    build: .
    container_name: product-service-goapp
    ports:
      - "8081:8081" # Host 8081 -> Container 8081
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo-product:27017/
  
