version: '3.8'

services:
  # The Database
  mongo:
    image: mongo:4.4
    container_name: mongo-order
    restart: always
    ports:
      - "27017:27017" # Allows you to connect from your host machine if needed
    volumes:
      - mongo-data:/data/db

  # Your Go Service
  order-service:
    build: .
    container_name: order-service-goapp
    ports:
      - "8085:8083" # Mapping your host port 8085 to container 8083
    environment:
      # This is the "magic" string that lets Go find the database
      - MONGO_URI=mongodb://mongo-order:27017
    depends_on:
      - mongo # Ensures Mongo starts before the app

volumes:
  mongo-data: # Persists your database even if the container is removed
