apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: micro-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
      - name: user-service
        image: samibaccouche9981/user-service:latest
        ports:
        - containerPort: 8080 # Port interne d'après ton docker-compose (8082:8080)
        env:
        - name: MONGO_URI
          value: "mongodb://mongo-user:27017/"
---
apiVersion: v1
kind: Service
metadata:
  name: goapp-user
  namespace: micro-app
spec:
  selector:
    app: user-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
