services:
  mongo:
    container_name: mongo-user
    image: mongo:4.4
    restart: always
    ports:
      - "27018:27017" # Host 27018 -> Container 27017


  goapp:
    build: .
    container_name: user-service-goapp
    ports:
      - "8080:8080" # Host 8080 -> Container 8080
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo-user:27017/
