name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        service: [cart-service, user-service, order-service, payment-service, product-service, notification-service]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Go Vet & Test
        run: |
          cd ${{ matrix.service }}
          [ -f go.mod ] || go mod init github.com/samibaccouche/${{ matrix.service }}
          go mod tidy
          go test -v ./...
  validate-gateway:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Check Nginx Config
        run: |
          # On nettoie le fichier pour le test de syntaxe
          sed -i '/upstream/,/}/d' nginx.conf 
          sed -i 's/proxy_pass http:\/\/.*;/proxy_pass http:\/\/localhost;/g' nginx.conf
          docker run --rm -v $(pwd)/nginx.conf:/etc/nginx/nginx.conf:ro nginx:alpine nginx -t
  sonarqube-analysis:
    runs-on: ubuntu-latest
    needs: build-and-test
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Important pour que Sonar puisse analyser l'historique git

      - name: SonarCloud Scan
        uses: SonarSource/sonarqube-scan-action@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }} 
        with:
          args: >
            -Dsonar.projectKey=samibaccouche_microservice_app
            -Dsonar.organization=samibaccouche
            -Dsonar.sources=.
  build-and-push-microservices:
      runs-on: ubuntu-latest
      needs: [sonarqube-analysis] # On attend que Sonar donne son feu vert
      strategy:
        matrix:
        # Liste de tes dossiers de services (vérifie bien l'orthographe)
          service: [cart-service, user-service, order-service, payment-service, product-service, notification-service]
    
      steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Login to Docker Hub
          uses: docker/login-action@v3
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}

        - name: Build and push
          uses: docker/build-push-action@v5
          with:
          # On se place dans le dossier du microservice (ex: ./cart-service)
            context: ./${{ matrix.service }}
            push: true
          # Remplace 'ton-user-docker' par ton vrai pseudo Docker Hub
            tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ matrix.service }}:${{ github.sha }}
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ matrix.service }}:latest



  build-and-push-gateway:
      runs-on: ubuntu-latest
      needs: [validate-gateway] # On attend que le test de syntaxe Nginx soit OK
      steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Login to Docker Hub
          uses: docker/login-action@v3
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}

        - name: Build and push Gateway
          uses: docker/build-push-action@v5
          with:
            context: .
            file: ./Dockerfile.gateway # On précise bien quel Dockerfile utiliser
            push: true
            tags: |
              ${{ secrets.DOCKERHUB_USERNAME }}/api-gateway:${{ github.sha }}
              ${{ secrets.DOCKERHUB_USERNAME }}/api-gateway:latest
  deploy-to-aks:
      runs-on: ubuntu-latest
      needs: [build-and-push-microservices, build-and-push-gateway]
      steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Setup Kubernetes Config
          run: |
            mkdir -p $HOME/.kube
            echo "${{ secrets.KUBE_CONFIG }}" | base64 -d > $HOME/.kube/config
            chmod 600 $HOME/.kube/config

        - name: Create Namespace
          run: |
            kubectl create namespace micro-app --dry-run=client -o yaml | kubectl apply -f -

        - name: Update and Deploy Manifests
          run: |
            DOCK_USER=${{ secrets.DOCKERHUB_USERNAME }}
            TAG=${{ github.sha }}
            sed -i "s|image: $DOCK_USER/\(.*\):latest|image: $DOCK_USER/\1:$TAG|g" k8s/*.yaml
            kubectl apply -f k8s/ -n micro-app

        - name: Verify Deployment
          run: |
            kubectl get pods -n micro-app
            kubectl get svc -n micro-app
